# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: NewsAPI CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  pipeline:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Lint Check
      run: make lint

    - name: Unit Test
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      run: make unit

    - name: Code Coverage
      run: make cover
    
    - name: Upload Coverage Report
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: johnpatek/newsapi-go
